# docker-compose.yml (travel_itinerary_manikandan project root)

services:
  # Backend API service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: madk-travel-blog-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    # The .env file in the project root will be used to provide
    # all necessary environment variables (NODE_ENV, PORT, secrets, etc.).
    env_file:
      - .env
    networks:
      - webnet
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend web service  
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: madk-travel-blog-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - webnet
    depends_on:
      - backend

networks:
  webnet:
    driver: bridge